services:
     frontend:
        build:
          context: ./frontend/
        ports:
          - 3000:3000 
        links:
          - backend 
     backend:
       build:
         context: .
       ports:
         - 5000:5000
       links:
         - db 
     db:
      image: mongo
      ports:
        - 27017:27017
      volumes:
          - mydata:/db/data
volumes:
    mydata:
